alias avim='NVIM_APPNAME=astronvim nvim'
alias bvim='NVIM_APPNAME=nvim-basic-ide nvim'
alias lazyvim='NVIM_APPNAME=LazyVim nvim'
alias kvim='NVIM_APPNAME=kickstart.nvim nvim'
alias mvim='NVIM_APPNAME=modern-neovim nvim'
