alias avim='NVIM_APPNAME=astronvim nvim'
alias bvim='NVIM_APPNAME=nvim-basic-ide nvim'
# alias lvim='NVIM_APPNAME=LazyVim nvim'
alias kvim='NVIM_APPNAME=kickstart.nvim nvim'
alias mvim='NVIM_APPNAME=modern-neovim nvim'
alias myvim='NVIM_APPNAME=myvim nvim'
alias tvim='NVIM_APPNAME=tvim nvim'
alias cvim='NVIM_APPNAME=cvim nvim'
alias ccvim='NVIM_APPNAME=ccvim nvim'
